### ISSUE TITLE
Linking libraries to ejected project

### ISSUE THREAD

**Issue by pyankoff** [react-community/create-react-native-app#161]
Hi, I'm trying to link libraries like react-native-billing and react-native-fcm to ejected project. I'm getting the following error:

## Description

I performed the following steps:
```
create-react-native-app test
cd test
yarn run eject
yarn add  react-native-billing --save
react-native link
```
Then start the Android project either with Android Studio or with `react-native run-android`

## Observed Behavior

The project doesn't compile

```
:react-native-billing:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/andrey/Dropbox/hack/test/node_modules/react-native-billing/android/src/main/java/com/idehub/Billing/InAppBillingBridge.java:410: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-billing:compileReleaseJavaWithJavac FAILED
```
Class that throws the error looks like that:
```
public class InAppBillingBridge extends ReactContextBaseJavaModule {
...
    @Override  <- this is the method that causes the error
   public void onNewIntent(Intent intent){
...
```
This should work on react-native >0.30, Is it possible that expo react fork https://github.com/expo/react-native/archive/sdk-15.0.0.tar.gz was not updated?

system: macOS
2. Phone/emulator/simulator & version: Android

* `npm ls react-native-scripts`: test@0.1.0
* `npm ls react-native`: react-native@0.42.0
* `npm ls expo`: expo@15.1.3 
* `node -v`: v7.5.0
* `npm -v`: 4.1.2
* `yarn --version`: 0.20.3
* `watchman version`: "version": "4.7.0"

**Comment by dikaiosune** [comment]
Thanks for the report! Which option did you select when you ejected?

**Comment by pyankoff** [comment]
Sure, i used 'Eject with ExpoKit'

**Comment by dikaiosune** [comment]
OK, cool. Can you try using the instructions [on this page](https://docs.expo.io/versions/v15.0.0/guides/expokit.html) instead of `react-native run-android`?

**Comment by dikaiosune** [comment]
cc @jesseruder

**Comment by jesseruder** [comment]
I don't see where `ReactContextBaseJavaModule` implements `onNewIntent`. Seems like it might just be a bug in the library.

**Comment by dikaiosune** [comment]
You know, this looks a lot like https://github.com/idehub/react-native-billing/issues/42.

**Comment by pyankoff** [comment]
My mistake, I didn't copy the full definition:
```
public class InAppBillingBridge extends ReactContextBaseJavaModule implements ActivityEventListener, BillingProcessor.IBillingHandler {
```
`onNewIntent` is implemented in [ActivityEventListener](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/ReactAndroid/src/main/java/com/facebook/react/bridge/ActivityEventListener.java)

**Comment by pyankoff** [comment]
@dikaiosune yep, I did run with Android Studio
@jesseruder I'm getting the same error from `react-native-fcm` library, there is an additional error with `onActivityResult` from the same [ActivityEventListener](https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/ReactAndroid/src/main/java/com/facebook/react/bridge/ActivityEventListener.java)

[expo react-native](https://github.com/expo/react-native/blob/exp-latest/ReactAndroid/src/main/java/com/facebook/react/bridge/ActivityEventListener.java) implements those methods too.

**Comment by pyankoff** [comment]
Seems like that's what's happening:
> When gradle can't find RN in this path, it doesn't throw an error, but instead looks in maven and finds an old version of it (0.20.0).
https://github.com/facebook/react-native/pull/12951

I've tried adding different paths to maven settings in `build.gradle`, nothing helps. Any advice?

**Comment by jesseruder** [comment]
It sounds like we agree the initial issue is a bug in another library. I don't really understand your second issue - could you follow the issue template when describing the second issue?

**Comment by pyankoff** [comment]
Sorry for confusion. What I was trying to say is that same issue happens when trying to link other libraries, not just react-native-billing. The issue happens because expo-react-native is not linked properly in gradle and libraries looking for react-native find it only on online maven repository where the latest available version is react-native@0.20.1.
Correct me if I'm wrong, but it seems like a CRNA issue.

**Comment by jesseruder** [comment]
It sounds like you didn't follow these instructions: https://docs.expo.io/versions/v15.0.0/guides/expokit.html#android

**Comment by pyankoff** [comment]
I did.

**Comment by jesseruder** [comment]
Ok, in that case can you please follow the issue template? I don't understand exactly what's happening.

**Comment by pyankoff** [comment]
I tried to follow issue template in the first message, you're right I missed mentioning the step with changin `compile project(':library-name')` to `compile(project(':library-name')) { exclude module: 'react-native' }`, though I performed it.

Here is a repo that reproduces the issue: https://github.com/pyankoff/crna-test

**Comment by dikaiosune** [comment]
@pyankoff thanks for the repro! Super helpful. I'll take a look at this soon and see if there's anything we can do to smooth out the dependency resolution.

**Comment by brentvatne** [comment]
Hello! We've done a bunch of work to make ExpoKit easier to use, hopefully that resolves the problems people have had with dependencies in this thread. Feel free to create another if you run into more issues :)
