### ISSUE TITLE
Linking libraries to ejected project

### ISSUE THREAD

**Issue by pyankoff** [react-community/create-react-native-app#160]
Hi, I'm trying to link libraries like react-native-billing and react-native-fcm to ejected project. I'm getting the following error:
```
test/node_modules/react-native-billing/android/src/main/java/com/idehub/Billing/InAppBillingBridge.java:410: error: method does not override or implement a method from a supertype
  @Override
   ^
```
InAppBillingBridge class looks like that:
```
public class InAppBillingBridge extends ReactContextBaseJavaModule {
...
    @Override  <- this is the method that causes the error
   public void onNewIntent(Intent intent){
...
```
This should work on react-native >0.30, Is it possible `https://github.com/expo/react-native/archive/sdk-15.0.0.tar.gz` was not updated?

**Comment by dikaiosune** [comment]
Can you please open a new issue and fill out the issue template with information about what exact steps you took to get there and the version information? Thanks!

**Comment by pyankoff** [comment]
Sure, sorry.
